#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        ddl-auto: none
#        database-platform: org.hibernate.dialect.H2Dialect
test2: value2